version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: propertydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data   # ✅ add persistent Redis volume

volumes:
  postgres_data:
  redis_data:              # ✅ define redis_data volume
